### ISSUE TITLE
Exception in Application start method

### ISSUE THREAD

**Issue by leon90dm** [AdoptOpenJDK/jitwatch#196] opened 2015-12-23 06:33 UTC
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:403)
	at com.sun.javafx.application.LauncherImpl.access$000(LauncherImpl.java:47)
	at com.sun.javafx.application.LauncherImpl$1.run(LauncherImpl.java:115)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ExceptionInInitializerError
	at javafx.scene.control.TableColumn.impl_setWidth(TableColumn.java:1259)
	at javafx.scene.control.TableColumn$8.invalidated(TableColumn.java:790)
	at javafx.beans.property.DoublePropertyBase.markInvalid(DoublePropertyBase.java:129)
	at javafx.beans.property.DoublePropertyBase.bind(DoublePropertyBase.java:203)

	at org.adoptopenjdk.jitwatch.ui.TableUtil.buildTableMemberAttributes(TableUtil.java:29)
	at org.adoptopenjdk.jitwatch.ui.JITWatchUI.start(JITWatchUI.java:569)
	at com.sun.javafx.application.LauncherImpl$5.run(LauncherImpl.java:319)

	at com.sun.javafx.application.PlatformImpl$5.run(PlatformImpl.java:219)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:182)
	at com.sun.javafx.application.PlatformImpl$4$1.run(PlatformImpl.java:179)

	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl$4.run(PlatformImpl.java:179)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:76)
Caused by: java.lang.NullPointerException
	at com.sun.t2k.MacFontFinder.initPSFontNameToPathMap(MacFontFinder.java:339)
	at com.sun.t2k.MacFontFinder.getFontNamesOfFontFamily(MacFontFinder.java:390)
	at com.sun.t2k.T2KFontFactory.getFontResource(T2KFontFactory.java:233)
	at com.sun.t2k.LogicalFont.getSlot0Resource(LogicalFont.java:184)
	at com.sun.t2k.LogicalFont.getSlotResource(LogicalFont.java:228)
	at com.sun.t2k.CompositeStrike.getStrikeSlot(CompositeStrike.java:86)
	at com.sun.t2k.CompositeStrike.getMetrics(CompositeStrike.java:132)
	at com.sun.javafx.font.PrismFontUtils.getFontMetrics(PrismFontUtils.java:31)
	at com.sun.javafx.font.PrismFontLoader.getFontMetrics(PrismFontLoader.java:466)
	at javafx.scene.text.Text.<init>(Text.java:153)
	at com.sun.javafx.scene.control.skin.Utils.<clinit>(Utils.java:52)
	... 13 more
--------
OS: OS X EI Capitan
Java version:
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by chriswhocodes** [comment] 2016-02-29 10:15
Hi, sorry for the long delay.
This is caused by JDK bug: https://bugs.openjdk.java.net/browse/JDK-8143907 which will be fixed in JDK7 update 95.
Sadly I suspect this fix will only be available to JDK7 users who pay for support as the last public release of JDK7 was update 79/80.
I would suggest upgrading to JDK8 if possible.

**Closed by chriswhocodes** 2016-02-29 10:15 UTC
Labels: investigate
