### ISSUE TITLE
Inlining Information: Erratic, unrepeatable  behavior.

### ISSUE THREAD

**Issue by KanataGuy** [AdoptOpenJDK/jitwatch#156] opened 2015-02-19 22:45 UTC
I just spent 6 hours installing and using JITwatch for the first time. Observations:

Installation:  Using maven - excellent, no errors, installed first time.

Using JITwatch: Generally speaking, the UI is intuitive and easy to use.

Specific issue: My only interest in using the JITwatch tool is to observe which hot methods the JVM/JIT is choosing to inline. Over repeated executions of the same Java class-main, the "inlining tree" display, gave erratic results, ranging between totally accurate (in terms of the tree 'nesting') to no inlining information whatsoever.

Question for the gurus: Is this erratic "inlining" behaviour a function of the JVM/JIT, unique to every instance of running a java main class, or is this a case of JITwatch having an "issue"?

**Comment by kcpeppe** [comment] 2015-02-20 06:48
On Feb 19, 2015, at 11:45 PM, KanataGuy <notifications@github.com> wrote:

> I just spent 6 hours installing and using JITwatch for the first time. Observations:
> 
> Installation: Using maven - excellent, no errors, installed first time.
> 
> Using JITwatch: Generally speaking, the UI is intuitive and easy to use.
> 
> Specific issue: My only interest in using the JITwatch tool is to observe which hot methods the JVM/JIT is choosing to inline. Over repeated executions of the same Java class-main, the "inlining tree" display, gave erratic results, ranging between totally accurate (in terms of the tree 'nesting') to no inlining information whatsoever.
> 
> Question for the gurus: Is this erratic "inlining" behaviour a function of the JVM/JIT, unique to every instance of running a java main class, or is this a case of JITwatch having an "issue"?
> 
> 
The JIT contains a lot of timing sensitive non-deterministic behavior that is in part due to the environment it is running in. If in the background, your email client decides to update it’s self, the JIT will feel that and …. If you load the JVM on top of a number of process that are 100% completely idle, the JIT will feel that and … If the group of counters being examined are slightly different due to *any* timing issue, the JIT will feel that and ….

JITWatch is brilliant! Chris will never get to meet a fraction of the people that are applauding this effort from him.

Regards,
Kirk

**Comment by chriswhocodes** [comment] 2015-02-20 08:59
Hi KanataGuy,

As Kirk mentioned, the JIT behaviour can be very sensitive to other processes on the machine.

Are you running your repeated executions using the JITWatch sandbox feature or are you outputting the hotspot logs from an external program? If the latter then a quick diff between log files will confirm the variations in JIT behaviour.

Running JITWatch on the same hotspot log should give repeatable results but in Java 8 there is a bug in the hotspot logging that means C1 (client compiler) inlining information is not nested correctly in the XML and so JITWatch can have problems visualising it.

I reported this: http://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2014-June/014912.html and it was fixed in Java 9 and backported to the upcoming Java 8 update 40: https://bugs.openjdk.java.net/browse/JDK-8049532

The JVM will nest the inlining information correctly when only the C2 compiler is used (Java 7 server VM and Java 8 with -XX:-TieredCompilation).

Hope that helps and thanks for your feedback!

Cheers,

Chris

**Comment by KanataGuy** [comment] 2015-02-20 12:36
I really appreciate you taking the effort to reply to my posting.

My use of JITwatch is during the 'design requirements analysis' phase of 
a project that will involve the use of pseudo real-time digital signal 
processing (DSP) of microphone input - all to be coded in Java. My 
initial experiments indicate that not only is this feasible in Java but 
that the DSP algorithm processor real-time loading is only about 5% on a 
typical target platform. - and that's without being too worried about 
writing 'optimized' Java code.

However.... I'm curious to compare the relative performance of Java and 
C for the execution of simple DSP vector primitives, e.g. 'add two 
arrays'. Initially, the timings for a Java method 'optimized for coding 
elegance' versus a totally optimized-for-speed C gave a ratio of  14:1 
(Java:C). Avoiding explicit or implicit 'new' object creation in the 
Java code reduced this ratio 6:1. Grooming the method details to 
'encourage' inlining of the method reduces this down to only 2:1.

So much for Java being 'slow' relative to C!

The more I learn about the operation of the JavaVM/JIT compiler the more 
impressed I get.

Have a great day!,

Andrew

**Comment by KanataGuy** [comment] 2015-02-20 12:52
Many thanks for your superb feedback!

I was comparing the Java 'hotspot - inline' logging that was being 
reported using -XX:+PrintInlining to my System.out with the logfile 
results being shown by JITwatch. The hotspot-inline logging reported to 
System.out was totally repeatable over very many runs whereas the 
JITwatch-reported results were 'all over the place'. Your comment below 
certainly would explain what I was observing:

/"Running JITWatch on the same hotspot log should give repeatable 
results but in Java 8 there is a bug in the hotspot logging that means 
C1 (client compiler) inlining information is not nested correctly in the 
XML and so JITWatch can have problems visualising it.//"/

I'm a relative newbie to Java but I come from a 25 year background in 
writing C/C++ real-time DSP applications. The more I use Java, its IDEs 
(Netbeans), its 3rd-party reusable code libraries and its development 
toolset (including JITwatch etc) the more impressed I become.

Once again, many thanks for your swift response to my posting!

Andrew.

**Comment by chriswhocodes** [comment] 2015-02-24 08:55
Closing as I believe the issue is caused by a HotSpot bug that will be fixed in 9 and 8u40.

**Closed by chriswhocodes** 2015-02-24 08:55 UTC
